### ISSUE TITLE
New header component

### ISSUE THREAD

**Issue by ahosgood** [LandRegistry/hmlr-frontend#2]

**Comment by AndyPorter** [comment]
### Internal service or system header

![example system name header](https://user-images.githubusercontent.com/4385428/181589096-cbcb6aa4-676d-4705-b3ca-19436da94d6c.png)
![example service name header](https://user-images.githubusercontent.com/4385428/181589148-40ca29f0-505c-45ef-88ba-17968f8afa63.png)
as per https://design-system.dwp.gov.uk/components/internal-service-header

because

1. this is all that is needed
2. we are learning from and making consistent with other government departments - so we, collectively, can reuse as much as possible and benefit from testing at scale

user needs:

- caseworkers/staff need to know what service or system they are using (for example so they know what system they are in, or can report an issue with a system)
- caseworkers/staff need to know where the top of the page is

#### header details

header is based on Gov header, in that:

- same height
- same background colour
- text has same foreground colour
- service/system name has same text properties, e.g. height, lineheight, etc
- all the gov breakpoints (screen sizes) are used - e.g. that text height changes to same as gov and the gov breakpoints

service/system name:
- the text is aligned to the left, matching the left alignment of the rest of the page content.  So at each breakpoint or page template width, the service name is aligned to the left (with the same margin+padding) the same as the rest of the page content - in the body and footer
- is a hyperlink (optional) that takes the user back to the main page/homepage of the service/system
- the hyperlink follows the same, hover, focus and visited behaviour as the DWP/Gov one
- preference is to have these as a) verbs not nouns, and b) never acronyms
- we might have to consider the maximum length the service/system name can be

Implementation, it probably makes sense to do what DWP have done, and use the standard gov classes for the same elements, and add HMLR specific override classes.


#### Potential additional considerations:

- a coloured border bar below the header to help the eye move between the end of the black header and the start of the main page content.  This should not be a colour that interferes with the colours used for primary actions or other key pages elements, like notifications, or error messages, warnings etc. (red, green, etc) 
- there may exist a need for additional features on some pages/systems and these might better be served as a page or context specific header.  e.g. a sub header.

#### things that are not required
and to consider if there arises a future need for additional header features

- saying who you work for (e.g. HMLR, HM Land Registry)
- logos or icons (use text)

**Comment by ahosgood** [comment]
Is the "Application Processing" or "Process Transfer and Charge application" the service name? Am I right in thinking we need to keep the functionality to add a URL to that service name?

**Comment by AndyPorter** [comment]
yes, there are the "service" or system name.  So map to the service name html/css element in the code.

I think it being a link is optional.  We know in application processing that it being a link to the 'home page' - well we have no home page.  We also know if we had one it would reset the application the user is processing - so i wouldn't also add one for that reason too.

If a system does have a logical hime page, then it makes sense that the system/service name is a link that returns there

**Comment by ahosgood** [comment]
Yes - the `serviceUrl` is a separate, optional field so we can have a service name that isn't a link.

**Comment by ahosgood** [comment]
Updated header component can be found here: https://hmlr-frontend-prealpha.herokuapp.com/?path=/story/components-header--standard
